### ISSUE TITLE
Rethink the usage of the Modelica License 2. 

### ISSUE THREAD

**Issue by dietmarw** [jkovacic/pow_el#1]
There is an issue with the Modelica License 2 in combination with GitHub. See https://github.com/impact/impact/blob/master/resources/docs/modelica2015/paper/impact.md#which-license-is-best-for-your-library for details.

**Comment by thorade** [comment]
Please have a look at the community page for this repo to see more files that could be added:
https://github.com/jkovacic/pow_el/community
https://github.com/blog/2380-new-community-tools

For the license, I would suggest to use BSD 3-clause
https://choosealicense.com/licenses/bsd-3-clause/
https://github.com/modelica/Modelica/issues/2320

**Comment by jkovacic** [comment]
As proposed, relicensed to 3-clause BSD license.
